package dev.tonholo.svgokt.conventions.fixtures

import java.io.File

/**
 * Writes the `GeneratedFixtures.kt` file that embeds every SVGO plugin
 * fixture (`*.svg.txt` under [fixturesDir]) as a `Map<String, String>` so
 * tests can run on every Kotlin Multiplatform target without filesystem
 * access.
 */
internal object FixturesGenerator {
    private val FIXTURE_FILENAME_REGEX = Regex("""^(.*)\.(\d+)\.svg\.txt$""")
    private const val RAW_TRIPLE_QUOTE = "\"\"\""

    // `${'"'}${'"'}${'"'}` — three separately interpolated double quotes so
    // raw-string delimiters never clash with fixture content containing `"""`.
    private const val ESCAPED_TRIPLE_QUOTE = "\${'\"'}\${'\"'}\${'\"'}"

    fun write(fixturesDir: File, outputDir: File) {
        val targetDir = outputDir.resolve("svgokt/integration")
        targetDir.mkdirs()
        val outputFile = targetDir.resolve("GeneratedFixtures.kt")

        val fixtureFiles = (fixturesDir.listFiles() ?: emptyArray())
            .filter { it.isFile && FIXTURE_FILENAME_REGEX.matches(it.name) }
            .sortedBy { it.name }

        val builder = StringBuilder()
        builder.appendLine("// GENERATED by generatePluginFixtureSources - DO NOT EDIT.")
        builder.appendLine("@file:Suppress(\"LargeClass\", \"MaxLineLength\")")
        builder.appendLine()
        builder.appendLine("package svgokt.integration")
        builder.appendLine()
        builder.appendLine("internal val pluginFixtureSources: Map<String, String> = mapOf(")
        for (file in fixtureFiles) {
            val text = file.readText()
                .replace("\r\n", "\n")
                .replace(RAW_TRIPLE_QUOTE, ESCAPED_TRIPLE_QUOTE)
            builder.append("    \"")
            builder.append(file.name)
            builder.append("\" to ")
            builder.append(RAW_TRIPLE_QUOTE)
            builder.append(text)
            builder.append(RAW_TRIPLE_QUOTE)
            builder.appendLine(",")
        }
        builder.appendLine(")")
        outputFile.writeText(builder.toString())
    }
}
